/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package live.houses;

import java.io.IOException;

import javafx.application.Application;
import javafx.fxml.FXMLLoader;
import javafx.scene.Group;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.image.Image;
import javafx.scene.layout.AnchorPane;
import javafx.scene.paint.Color;
import javafx.stage.Stage;

public class App extends Application {

    // public static void main(String[] args){
    //     launch(args);
    // }

    // public void start(Stage stage) throws Exception{
    //     //Stage stage = new Stage();
    //     Group root = new Group();
    //     Scene scene = new Scene(root, Color.BLACK);

    //     // Image icon = new Image("abazo.png");
    //     // stage.getIcons().add(icon);

        


    //     stage.setScene(scene);
    //     stage.show();
    // }
    
    @Override
    public void start(Stage stage) {

        try {
            System.out.println(getClass().getResource("/fxml/login.fxml"));
            Parent root = FXMLLoader.load(getClass().getResource("/fxml/login.fxml"));
            Scene scene = new Scene(root);
            stage.setScene(scene);
            stage.show();

            // Create an FXMLLoader Instance
            // FXMLLoader fxmlLoader = new FXMLLoader(getClass().getResource("/fxml/login.fxml"));
            // // Call setRoot on the instance
            // fxmlLoader.setRoot(new AnchorPane());
            // // Call the load() function on the file
            // Parent root = fxmlLoader.load();
            // Scene scene = new Scene(root);
            // stage.setScene(scene);
            // stage.show();
        } 
        catch(IOException e){
            e.printStackTrace();
        } 
        
    }

    public static void main(String[] args) {
        launch();
    }
}

