/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package livehouses;

import java.io.IOException;
import java.util.Scanner;
import javafx.application.Application;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.stage.Stage;
import livehouses.menu.MenuManager;

public class App extends Application {
    static AppState state = new AppState();
    static MenuManager menuManager = new MenuManager(state);
    public static Scanner scanner = new Scanner(System.in);
    public static String VERSION = "v0.1.0";

    @Override
    public void start(Stage stage) {

        try {
            System.out.println(getClass().getResource("/fxml/login.fxml"));
            Parent root = FXMLLoader.load(getClass().getResource("/fxml/login.fxml"));
            Scene scene = new Scene(root);
            stage.setScene(scene);
            stage.show();
        }
        catch(IOException e){
            System.err.println("Error loading login.fxml");
            e.printStackTrace();
        }
    }

    public static void main(String[] args) {
        Application.launch();
    }
}
