/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package live.houses;

import javafx.application.Application;
import javafx.scene.Scene;
import javafx.scene.control.Label;
import javafx.scene.layout.StackPane;
import javafx.stage.Stage;

public class App extends Application {
    @Override
    public void start(Stage primaryStage) {
        // Create a label with the text "Hello, World!"
        Label helloLabel = new Label("Hello, World!");

        // Create a layout pane (StackPane) and add the label to it
        StackPane root = new StackPane();
        root.getChildren().add(helloLabel);

        // Create a scene and set the layout pane as its root
        Scene scene = new Scene(root, 300, 200);

        // Set the scene on the primary stage (window)
        primaryStage.setScene(scene);
        primaryStage.setTitle("Hello, World JavaFX App");
        primaryStage.show();
    }

    public static void main(String[] args) {
        // Launch the JavaFX application
        launch(args);
    }
}

